### ISSUE TITLE
Scrolling in context menu

### ISSUE THREAD

**Issue by Noxtal** [retejs/context-menu-plugin#23]
Hi! I've started using Rete.js 2 or 3 days ago and I really enjoy your plugin :)

Is it or would it be possible to have a enable scrolling if there are too many items in the context menu? I've all Math class functions implemented automatically in nodes, so there is a lot to display and it overflows out of my view...

Thanks in advance and sorry for English mistakes

Greatings from Québec, Canada!
ZedeV2

**Comment by Ni55aN** [comment]
Hi!

> I've all Math class functions implemented automatically in nodes

How many items does it have? The nested subitems are more preferable in terms of UX. However, you can add global styles:

```css
.context-menu {
    max-height: 60vh;
    overflow-y: auto;
}
```

but in this case mouse wheel scrolling doesn't work (and the native scroll looks out of place)

**Comment by Noxtal** [comment]
Really sorry for the late answer... 


> How many items does it have?

I've counted 35 functions in the Math class, so there is a lot to display :/

For your code snippet, I tried it and it looks really off (like really)... 

What I would like is a way that a constant amount of items in the submenu would be available and we could scroll in the submenu only. 
But I don't know if it is even possible easily.

Thank you!
ZedeV2

**Comment by Ni55aN** [comment]
Look at the selectors in Item.vue. There is `.subitems` selector

**Comment by Noxtal** [comment]
> Look at the selectors in Item.vue. There is `.subitems` selector

I'll check that out!

For now, I've found this option that behaves better than I thought:
```css
.subitems {
  /* Adjustable Height */
  height: 200px;
  overflow-y: scroll;
  overflow-x:hidden;
}

::-webkit-scrollbar {
  width: 10px;
}

::-webkit-scrollbar-track {
  background: #fff;
}

::-webkit-scrollbar-thumb {
  background: rgb(110, 136, 255);
}

::-webkit-scrollbar-thumb:hover {
  background: rgb(69, 103, 255);
}
```

Now, I'm on the process of thinking on how I can apply this on the search results...
to be continued 

ZedeV2
