### ISSUE TITLE
Customize styling of context menu

### ISSUE THREAD

**Issue by Keksparade** [retejs/context-menu-plugin#9]
Hi,

is it possible to customize the style of the context menu (e.g. width, background)? What is the proper way to do it?

![contextmenu](https://user-images.githubusercontent.com/15687427/51977342-7befaa80-2487-11e9-95c9-ca1ea31157f0.png)

Thanks for the amazing library and support!

**Comment by Ni55aN** [comment]
Since v0.3.4 you can define custom Vue.js Menu component.

Example (without single file components):

```js
editor.use(ContextMenuPlugin, {
 vueComponent: {
            template: `<div class="context-menu"
            ref="menu" 
            v-if="visible"
            v-bind:style="style"
            @mouseleave="timeoutHide()" @mouseover="cancelHide()" @contextmenu.prevent="">
            <Item v-for="item in filtered" :key="item.title" :item="item" :args="args" :delay="delay / 2"></Item>
            </div>`,
            extends: { ...ContextMenuPlugin.Menu, _scopeId: null, render: null },
            components: {
                Item: {
                    name: 'Item',
                    template: `<div class="item"
                        @click="onClick($event)"
                        @mouseover="showSubitems()"
                        @mouseleave="timeoutHide()"
                        :class="{ hasSubitems }"
                        > {{item.title}}
                        <div class="subitems" v-show="hasSubitems && this.visibleSubitems">
                            <Item v-for="subitem in item.subitems"
                            :key="subitem.title"
                            :item="subitem"
                            :args="args"
                            :delay="delay"
                            ></Item>
                        </div>
                    </div>`,
                    extends: { ...ContextMenuPlugin.Item, _scopeId: null,  render: null }
                }
            }
        }
});
```

```css

        .context-menu {
            left: 0;
            top: 0;
            position: fixed;
            padding: 10px;
            width: 140px;
            margin-top: -20px;
            margin-left: -60px;
        }

        .context-menu .item, .context-menu .subitem {
            color: #fff;
            padding: 4px;
            border-bottom: 1px solid grey;
            background-color: grey;
            cursor: pointer;
            width: 100%;
            position: relative;
        }

        .context-menu .search {
            background: red;
        }

        .context-menu .item.hasSubitems:after {
            content: '►';
            position: absolute;
            opacity: 0.6;
            right: 5px;
            top: 5px;
        }
        .context-menu .item .subitems {
            position: absolute;
            top: 0;
            left: 100%;
            width: 120px;
        }
```

Using single-file components you need to extend the standard components imported from the plugin.

```js
import { Menu, Item, Search } from 'rete-context-menu-plugin';

```
